[package]
name = "fractal"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Danny Stoll"]
repository = "https://github.com/dannystoll1/fractal-explorer"
description = "A tool for studying discrete time dynamical systems - Native UI"

[dependencies]
eframe = ">=0.22.0"
fractal_gui = { version = "*", path = "../gui" }

[features]
serde = ["fractal_gui/serde"]
