[package]
name = "fractal"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Danny Stoll"]
repository = "https://github.com/dannystoll1/fractal-explorer"
description = "A tool for studying discrete time dynamical systems - Native UI"

[dependencies]
eframe = "0.23.0"
fractal_app = { version = "*", path = "../app" }

[features]
serde = ["fractal_app/serde"]

[package.metadata.bundle]
name = "Fractal Explorer"
identifier = "io.github.dannystoll1.fractal-explorer"
version = "0.4.0"
icon = ["../docs/icons/*.png", "../docs/icons/*.icns"]
short_description = "A tool for exploring dynamical systems on complex manifolds."
osx_minimum_system_version = "10.7"
