[package]
name = "fractal"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Danny Stoll"]
repository = "https://github.com/dannystoll1/fractal-explorer"
description = "A tool for studying discrete time dynamical systems - Native UI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
fractal_lib = { version = ">=0.2.0", path = "../lib" }

[features]
serde = ["fractal_lib/serde"]
