[workspace]
resolver = "2"

members = [
    "crates/app",
    "crates/bin",
    "crates/common",
    "crates/coloring",
    "crates/core",
    "crates/gui",
    "crates/wasm",
    "crates/profiles",
    "crates/poly_solve",
    "crates/scripting/loader",
    "crates/scripting/output",
]


[profile.dev]
opt-level = 2
debug = false
overflow-checks = false
