[package]
name = "fractal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = ">=0.4.3"
ndarray = ">=0.15.6"
image = "*"
eframe = ">=0.21.3"
egui_extras = { version = ">=0.21.0", features = ["image"] }
show-image = { version = ">=0.13.1", features = ["macros", "image", "save"] }
num = "0.4.0"
