[workspace]
resolver = "2"

members = [
    "common",
    "core",
    "gui",
    "bin",
    "wasm",
    "profiles",
    "poly_solve",
]


[profile.dev]
opt-level = 2
debug = false
overflow-checks = false
