[workspace]
resolver = "2"
exclude = ["vendor/*"]

members = [
  "crates/app",
  "crates/bin",
  "crates/common",
  "crates/coloring",
  "crates/core",
  "crates/gui",
  "crates/wasm",
  "crates/profiles",
  "crates/poly_solve",
  "crates/scripting/loader",
  "crates/scripting/output",
]

default-members = [
  "crates/app",
  "crates/bin",
  "crates/common",
  "crates/coloring",
  "crates/core",
  "crates/gui",
  "crates/wasm",
  "crates/profiles",
  "crates/poly_solve",
]


[profile.dev]
opt-level = 2
debug = false
overflow-checks = false

[profile.release]
lto = true
# codegen-units = 1
panic = "abort"


[workspace.dependencies]
egui = "0.34"
eframe = "0.34"
epaint = "0.34"
egui_extras = "0.34"
egui_file = { path = "vendor/egui_file" }
egui_dock = { path = "vendor/egui_dock" }
image = "0.25"

itertools = "0.14"
lazy_static = "1.5"
ndarray = "0.17"
rayon = "1.11"

num-complex = "0.4"
num-rational = "0.4"
num-traits = "0.2"

toml = "1.1"
derive_more = { version = "2.1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.5"


[workspace.lints.clippy]
all = { level = "allow", priority = -3 }
style = { level = "warn", priority = -2 }
complexity = { level = "warn", priority = -2 }
perf = { level = "deny", priority = -2 }
correctness = { level = "deny", priority = -2 }
nursery = { level = "warn", priority = -2 }
pedantic = { level = "warn", priority = -2 }
todo = { level = "warn", priority = -1 }
missing-panics-doc = "allow"
missing-errors-doc = "allow"
doc_markdown = "allow"
module-name-repetitions = "allow"
cast-possible-truncation = "allow"
cast-possible-wrap = "allow"
cast-precision-loss = "allow"
cast-sign-loss = "allow"
enum-glob-use = "allow"
option-if-let-else = "allow"
wildcard-imports = "allow"
cognitive-complexity = "allow"

allow-attributes = "warn"
allow-attributes-without-reason = "warn"
# cargo-common-metadata = "warn"
clone-on-ref-ptr = "warn"
dbg-macro = "warn"
decimal-literal-representation = "warn"
default-union-representation = "deny"
doc-paragraphs-missing-punctuation = "warn"
empty-structs-with-brackets = "warn"
filetype-is-file = "warn"
if-then-some-else-none = "warn"
infinite-loop = "deny"
# multiple-crate-versions = "warn"
mutex-atomic = "warn"
pathbuf-init-then-push = "warn"
rc-buffer = "warn"
rc-mutex = "warn"
redundant-test-prefix = "warn"
same-name-method = "warn"
string-lit-chars-any = "warn"
too-long-first-doc-paragraph = "warn"
return-and-then = "warn"
unwrap-used = "deny"
verbose-file-reads = "warn"
str-to-string = "warn"
unused-trait-names = "warn"
