[package]
name = "fractal"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = ">=0.4.3"
ndarray = ">=0.15.6"
image = "*"
eframe = ">=0.21.3"
egui_extras = { version = ">=0.21.0", features = ["image"] }
num = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.7.0"
dyn-clone = "1.0.11"
epaint = "0.21.0"
input-macro = "0.2.0"
thread_local = "1.1.7"
num_cpus = "1.15.0"
# fractal_derive = { path = "../fractal_derive" }
criterion = "0.4.0"
derive_more = { version = "0.99.17", features = ["from", "add", "iterator"] }
serde = { version = "1.0.163", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "eframe/serde", "epaint/serde", "num-complex/serde"]
