[package]
name = "dynamo"
version = "1.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Danny Stoll"]
repository = "https://github.com/dannystoll1/dynamo"
description = "A tool for studying discrete time dynamical systems - Native UI"

[dependencies]
eframe = { workspace = true }
dynamo_app = { version = "*", path = "../app" }

[features]
serde = ["dynamo_app/serde"]

[package.metadata.bundle]
name = "Dynamo"
identifier = "io.github.dannystoll1.dynamo"
version = "1.1.0"
icon = ["../../docs/icons/*.png", "../../docs/icons/*.icns"]
short_description = "A tool for exploring dynamical systems on complex manifolds."
osx_minimum_system_version = "10.7"
