[package]
name = "fractal_gui"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.166", features = ["derive"], optional = true }
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = { version = ">=0.22.0", features = ["image"] }
egui_file = ">=0.9.0"
egui_dock = ">=0.6.3"
epaint = ">=0.22.0"
input-macro = ">=0.2.0"
seq-macro = "0.3.4"
fractal_core = { version = "*", path = "../core" }
fractal_common = { version = "*", path = "../common" }
fractal_profiles = { version = "*", path = "../profiles" }

[features]
serde = ["dep:serde", "eframe/serde", "epaint/serde", "fractal_core/serde", "fractal_common/serde"]
mpsolve = ["fractal_core/mpsolve", "fractal_common/mpsolve"]
