[package]
name = "fractal_profiles"
version = "0.4.0"
edition = "2021"

[dependencies]
fractal_common = {version = "*", path = "../common"}
fractal_core = {version = "*", path = "../core"}
seq-macro = "0.3.5"

[lib]
name = "fractal_profiles"
path = "lib.rs"
