[package]
name = "dynamo_profiles"
version = "0.5.1"
edition = "2021"

[dependencies]
dynamo_common = {version = "*", path = "../common"}
dynamo_core = {version = "*", path = "../core"}
seq-macro = "0.3.5"

[lib]
name = "dynamo_profiles"
