[package]
name = "user_profiles"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fractal_gui = { version = "*", path = "../gui" }
fractal_core = { version = "*", path = "../core" }
fractal_common = { version = "*", path = "../common" }

