# This is a sample script to show capabilities.
# Further examples may be found in user_scripts/examples.
# You can change this default by editing user_scripts/.default.toml.

[metadata]
# Display name.
# May be any unicode string.
name = "QuadRat Per(2, Î»)"

# Name used internally.
# Must be alphanumeric and unique to this script.
short_name = "quadrat_per_2_l"

[names]
# Dynamical variable
variable = "z"

# Pixel location
selection = "t"

[constants]
# Any constants you want to define
mu = "2-i"

[parameters]
# Any parameters for the system, described in terms of the selection
# If you just want a Julia set, you can leave this section empty.
a = "t**2 * (mu + mu*t - 4) / 4"
b = "t * (mu*t - 4) / 4"

[dynamics] 
# Initial point. May depend on selection, parameters, and constants.
# Perfectly valid in this context would be `start = "3*t - mu/a"`
start = 0

# Dynamical map. Cannot depend directly on selection.
# If it does, just add a parameter representing the selection,
# e.g. c = "t" under [parameters]
map = "(z**2 + a)/(z**2 + b)"
