[package]
name = "script_loader"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
pyo3 = { version = "0.19", features = ["extension-module", "num-complex"] }
num-complex = { version = "0.4.4", features = ["serde"] }
regex = "1.10.0"
lazy_static = "1.4.0"
libloading = "0.8.1"
dynamo_gui = { version = "*", path = "../../gui", features = ["scripting"] }
dynamo_core = { version = "*", path = "../../core" }
dynamo_common = { version = "*", path = "../../common" }
sha256 = "1.4.0"
